[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
  # Set linker script.
  "-Clink-arg=-Tsrc/linker.ld",
  # Force the compiler to not optimize fp.
  "-Cforce-frame-pointers=yes",
]
